language: java
dist: bionic
sudo: false

jdk:
  - openjdk11
  - openjdk13
  - oraclejdk11
  - oraclejdk13
 
script:
  - gradlew clean test distFull

notifications:
    webhooks: https://www.travisbuddy.com/
