name: Build

on: 
  push:
    branches:
      - unstable
  pull_request:
    branches:
      - unstable

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
# Not sure why this is needed, per a support issue (https://github.com/gradle/gradle-build-action/issues/517) it should not
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute Gradle build
        run: ./gradlew clean check build dist
# If wanting to serialize all the engines during build
#        run: ./gradlew clean serializeEnginesDist build dist
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: openrocket_build_${{ github.run_number }}
          path: ${{github.workspace}}/build/lib/openrocket*.jar

