name: Build

on: 
  push:
    branches:
      - test_gradle
  pull_request:
    branches:
      - test_gradle

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
#      - name: Gradle build
#        run: ./gradlew clean test distFull
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: openrocket_build_${{ github.run_number }}
#          path: ${{github.workspace}}/swing/build/jar/OpenRocket.jar

